# Example Config
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:
      dhcp4: no #
      addresses: [192.168.10.246/24]
      gateway4 : 192.168.10.1
      nameservers:
        search  : [asepready, asepready,com]
        addresses: [8.8.8.8, 8.8.4.4]
